"""add async fields to regulation runs

Revision ID: 3850f57a6da7
Revises: 17a1cea4a79a
Create Date: 2026-04-27 20:21:08.140689

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3850f57a6da7"
down_revision: str | Sequence[str] | None = "17a1cea4a79a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("regulation_runs", sa.Column("rq_job_id", sa.String(length=255), nullable=True))
    op.add_column(
        "regulation_runs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "regulation_runs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "regulation_runs",
        "error_message",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "regulation_runs",
        "error_message",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.drop_column("regulation_runs", "finished_at")
    op.drop_column("regulation_runs", "started_at")
    op.drop_column("regulation_runs", "rq_job_id")
    # ### end Alembic commands ###
