"""add regulation_runs

Revision ID: 4ce9c79037ba
Revises: 854dee9d166e
Create Date: 2026-04-15 22:14:37.133987

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4ce9c79037ba"
down_revision: str | Sequence[str] | None = "854dee9d166e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
