"""add regulations_run

Revision ID: 854dee9d166e
Revises: d537d00a87b0
Create Date: 2026-04-15 21:40:32.233852

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "854dee9d166e"
down_revision: str | Sequence[str] | None = "d537d00a87b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
